version: 2.1

orbs:
  android: circleci/android@2.5.0

jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: medium
      tag: default
    #docker:
    #- image: cimg/android:2024.07.1
    steps:
    #- checkout
    - run:
        name: Echo
        command: |
          echo "Hello World"
    - run:
        name: Get directory
        command: | 
          ls -lah /home/circleci/project
    - run: 
        name: Install deps
        command: | 
          bundle install
    - run: 
        name: Get content of Gemfile
        command: |
          cat Gemfile
    - run: 
        name: Make build
        command: |
          bundle exec fastlane build

workflow:
  develop-build:
    jobs:
      - build